version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    volumes:
      - ./data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/dbname
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development

  